### ISSUE TITLE
Many products with Images not centre aligned #147

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#49]
There are many products with Images, which are not aligned at the centre. They are usually Right Aligned.
![147](https://cloud.githubusercontent.com/assets/10416359/6551911/6bb35302-c661-11e4-89d2-670004b181db.jpg)

**Comment by uuaqarahmed** [comment]
@kamrannaqvi This is not image alignment issue, instead it is due to image dimensions and the white area around it. See attached example for details: 

![alignment](https://cloud.githubusercontent.com/assets/527591/6603186/42889838-c842-11e4-98d6-94f2816d8686.png)

Also, text alignment in center is not recommended as it ruins the overall layout. See example below:

![middle-align](https://cloud.githubusercontent.com/assets/527591/6603263/b7f1c338-c842-11e4-8d25-ab88a891eeb1.png)

For the sake of design, it is recommended that it should be kept as is.

**Comment by kamrannaqvi** [comment]
Agreed.
